server:
  port: 9001
spring:
  application:
    name: tensquare-base  #指定服务名
    #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf-8
    username: root
    password: root
    #配置jpa
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true  #自动生成表结构
  rabbitmq:
    host: 192.168.200.133
#添加Eureka-client配置信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka #注册中心地址
  instance:
    prefer-ip-address: true
