server:
  port: 6868 #服务端口
spring:
  application:
    name: coco-eureka #当前应用的名称，在此微服务中，这个name我们可以不用指定
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，本身就是Eureka服务，所以无需注册
    fetchRegistry: false #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/  #暴露当前Eureka服务端的地址，用于Eureka客户端与Eureka服务端进行交互
